### ISSUE TITLE
Human readable number translator?

### ISSUE THREAD

**Issue by elgs** [williamFalcon/SwiftArmyKnife#2]
Thanks for the awesome Swiss Knife library. It makes life a lot easier to write Swift code. Now I'm looking for a function that could translate a number to a more human readable format, e.g. 1024 -> 1K, 123456789 -> 117.74M, and etc. Not sure if this library have anything like this?

**Comment by williamFalcon** [comment]
Hey, I have something like this written. I'll load it into the library over the next few weeks! Thanks for the support!

**Comment by williamFalcon** [comment]
pushed new updates. Will implement this shortly! The library currently has 1000 -> k
